name: fan_simple_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=2.19.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    sizer: ^2.0.15
    get: ^4.6.5
    shared_preferences: ^2.2.1
    equatable: ^2.0.5
    google_fonts: ^5.0.0
    pull_to_refresh: ^2.0.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
