name: fan_simple_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=2.19.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    sizer: ^2.0.15
    get: ^4.6.5
    shared_preferences: ^2.2.1
    equatable: ^2.0.5
    google_fonts: ^5.0.0
    pull_to_refresh: ^2.0.0
    firebase_core: ^2.15.1
    firebase_auth: ^4.9.0
    dio: ^5.3.2
    retrofit: ^4.0.1
    json_annotation: ^4.8.1
    flutter_secure_storage: ^9.0.0
    freezed_annotation: ^2.4.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    build_runner: ^2.4.6
    flutter_gen_runner: ^5.3.1
    retrofit_generator: ">=5.0.0 <6.0.0"
    json_serializable: ^6.7.1

flutter:
    uses-material-design: true
