// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwmXhafXr3ne7E-cDkVYx5JYf3RjHr48',
    appId: '1:1057705874484:android:802f6a01a6c6344cb1a661',
    messagingSenderId: '1057705874484',
    projectId: 'rocketmall---seller-center',
    storageBucket: 'rocketmall---seller-center.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fOuZlCEraEjWPPT45kYB91-WY8WOf4I',
    appId: '1:1057705874484:ios:9d8af0882f394d39b1a661',
    messagingSenderId: '1057705874484',
    projectId: 'rocketmall---seller-center',
    storageBucket: 'rocketmall---seller-center.appspot.com',
    iosClientId: '1057705874484-8jqlnvi2sef9603bthdf7cpnr6ogpbl7.apps.googleusercontent.com',
    iosBundleId: 'com.rocketmall.sellercenter',
  );
}
