const Map<String, String> en = {
  // General Pop Up
  // Delete
  'txt_confirmation_dialog_title': 'Are you sure',
  'txt_confirmation_dialog_description':
      'You will not be able to revert this action',

  'txt_name': 'name',
  'txt_email': 'Email',
  'txt_password': 'Password',
  'txt_menu_home': 'Home', // with argument using %s
  'txt_menu_dialog': 'Dialogs',
  'txt_menu_maps': 'Maps',
  'txt_menu_other': 'Others',
  'txt_menu_login': 'Login',
  'txt_menu_detail': 'Detail',
  'txt_empty_user': 'Data users not found',
  'txt_error_title': 'Something when wrong',
  'txt_error_general': 'Oops something when wrong...',
  'txt_used': 'Used',

  // Bottom Navigation
  'txt_home': 'Dashboard',
  'txt_order': 'Order',
  'txt_product': 'Product',
  'txt_message': 'Chat',
  'txt_store': 'My Store',

  // Onboarding
  'onboard_first': 'Analysis your store with simple and easier dashboard',
  'onboard_second': 'Make trust and relation with your customer, with chat',
  'onboard_third': 'Track your product and order with easier feature',
  'skip': 'Skip',
  'login': 'Login',

  // Product
  'txt_catalog': 'Catalog',
  'txt_catalog_active': 'Active Catalog',
  'txt_bulk_update': 'Bulk Update',
  'txt_edit_all': 'Edit All',
  'txt_variant': 'Variant',
  'txt_price': 'Price',
  'txt_discount': 'Discount',
  'txt_request': 'Request',
  'txt_requested': 'Requested',
  'txt_rejected': 'Rejected',

  'txt_catalog_detail': 'Catalog Detail',
  'txt_product_detail': 'Product Detail',
  'txt_product_detail_description': 'Input detail product descriptions',
  'txt_product_image': 'Product Image',
  'txt_product_rating': 'Product Rating',
  'txt_catalog_edit': 'Edit Catalog',
  'txt_catalog_add': 'Add Catalog',

  // Catalog Detail
  'txt_brand': 'Brand',
  'txt_category': 'Category',
  'txt_description': 'Description',
  'txt_variants': 'Variants',
  'txt_variants_description': 'Input single variant product description',
  'txt_multi_variants_description': 'Input multi variant product description',
  'txt_dimension': 'Dimension',
  'txt_dimension_description': 'Input dimension of the product',
  // Variant
  'txt_single_variant_sku': 'Single Variant SKU (Stock Keeping Unit)',
  'txt_multi_variant_sku': 'Variant SKU (Stock Keeping Unit)',
  'txt_normal_price': 'Normal Price',
  'txt_cost_price': 'Cost Price',
  'txt_cost_price_initial': 'Cost Price (Initial Capital)',
  'txt_discount_price': 'Discount Price',
  'txt_weight': 'Weight',
  'txt_color_size': 'Color / Size',
  'txt_sku': 'SKU',
  'txt_set_multiple_at_once': 'Set Multiple At Once',
  'txt_set_multiple_at_once_description': 'Set SKU, price, stock, etc. at once',
  // Dimension
  'txt_width': 'Width',
  'txt_height': 'Height',
  'txt_depth': 'Depth',
  // Status
  'txt_status': 'Status',
  'txt_active': 'Active',
  'txt_inactive': 'Inactive',
  // See All
  'txt_see_all': 'See All',
  'txt_see_less': 'See Less',

  'txt_add_up_to': 'Add up to 3 images',
  'txt_single_variant_title': 'Single Variant',
  'txt_multi_variant': 'Multi Variant',
  'txt_add_variations': 'Add Variations',
  'txt_variations': 'Variations',
  'txt_variation_name': 'Variation Name',
  'txt_option_name': 'Option Name',

  'txt_total_of_order': 'Total of Order',
  'txt_day': 'Day',
  'txt_month': 'Month',
  'txt_year': 'Year',
  'txt_all_period': 'All Period',
  'txt_sold': 'Sold',
  'txt_chat': 'Chat',
  'txt_type_message_here': 'Type message here',
  'txt_select_variant': 'Select Variant',
  'txt_select_all': 'Select All',
  'txt_set': 'Set',
  'txt_remove_variation': 'Remove Variation',
  'txt_choose_date': 'Choose Date',

  'txt_filter': 'Filter',
  'txt_reset': 'Reset',
  'txt_all': 'All',
  'txt_unread': 'Unread',
  'txt_read': 'Read',
  'txt_date': 'Date',

  // Variant Detail
  'txt_variant_detail': 'Detail Variant',

  // Variant Edit
  'txt_variant_edit': 'Edit Variant & Inventory',
  'txt_variant_edit_single_sku': 'Single Variant SKU (Stock Keeping Unit)',
  'txt_variant_edit_sku': 'Variant SKU (Stock Keeping Unit)',
  'txt_variant_edit_normal_price': 'Normal Price (Rp)',
  'txt_variant_edit_cost_price': 'Cost Price (Initial Capital) (Rp)',
  'txt_variant_edit_discount_price': 'Discount Price (Rp)',
  'txt_variant_edit_weight': 'Weight (Kg)',

  // Brand Detail
  'txt_brand_detail': 'Detail Brand',
  'txt_brand_name': 'Brand Name',
  'txt_brand_description': 'Description',
  // Brand Add
  'txt_brand_add': 'Add Brand',
  'txt_brand_add_name': 'Brand Name',
  'txt_brand_add_description': 'Description',
  'txt_input_brand_name': 'Input Brand Name',
  'txt_input_brand_description': 'Input Description',

  // Dashboard
  'txt_store_analysis': 'Store Analysis',
  'txt_product_sold': 'Product Sold',
  'txt_store_visit': 'Store Visit',
  'txt_last_day': 'vs last day',
  'txt_profit': 'Profit',
  'txt_sales_revenue': 'Sales Revenue',
  'txt_cost_of_product': 'Cost of Product',
  'txt_cost_of_voucher_discount': 'Cost of Voucher Discount',
  'txt_cost_of_commision': 'Cost of Commision',
  'txt_cost_of_complained_order': 'Cost of Complained Order',

  'txt_stock_reminder': 'Stock Reminder',
  'txt_product_name': 'Product Name',
  'txt_out_of_stock': 'Out of Stock',

  'txt_most_sold_product': 'Most Sold Product',
  'txt_top_product': 'Top Product',
  'txt_stock': 'Stock',
  'txt_show_more': 'Show More',
  'txt_show_less': 'Show Less',

  'txt_color': 'Color',
  'txt_add_option': 'Add option',
  'txt_size': 'Size',
  'txt_order_detail': 'Order Detail',

  // Order
  'txt_search_voucher': 'Search Voucher',
  'txt_search': 'Search',
  'txt_paid': 'Paid',
  'txt_on_process': 'On Process',
  'txt_on_delivery': 'On Delivery',
  'txt_delivered': 'Delivered',
  'txt_process': 'Process',
  'txt_waiting_for_payment': 'Waiting for payment',
  'txt_on_processed': 'On Processed',
  'txt_completed': 'Completed',
  'txt_canceled': 'Canceled',
  'txt_complained': 'Complained',
  'txt_waiting_for_return': 'Waiting for return',
  'txt_waiting_for_refund': 'Waiting for refund',
  'txt_waiting_for_return_and_refund': 'Waiting for return and refund',
  'txt_completed_complained': 'Completed Complained',
  'txt_rejected_complained': 'Rejected Complained',
  'txt_sort': 'Sort',
  'txt_shipment_method': 'Shipment Method',
  'txt_deliver_order': 'Deliver Order',
  'txt_delivery_receipt': 'Delivery Receipt',
  'txt_waiting_for_replacement': 'Waiting for Replacement',
  'txt_waiting_for_redelivery': 'Waiting for Redelivery',
  'txt_watiing_for_return': 'Waiting for Return',
  'txt_waiting_payment': 'Waiting Payment',
  'txt_cancelled': 'Cancelled',
  'txt_input_receipt': 'Input Receipt',
  'txt_order_status': 'Order Status',
  'txt_order_id': 'Order ID',
  'txt_invoice_id': 'Invoice ID',
  'txt_ordered_at': 'Ordered At',
  'txt_customer': 'Customer',
  'txt_phone': 'Phone',
  'txt_notes': 'Notes',
  'txt_vendor_notes': 'Vendor Notes',
  'txt_product_list': 'Product List',
  'txt_shipping': 'Shipping',
  'txt_courier': 'Courier',
  'txt_self_delivery': 'Self Delivery',
  'txt_jnt': 'JNT',
  'txt_sicepat': 'SiCepat',
  'txt_pos': 'Pos Indonesia',
  'txt_tracking_number': 'Tracking Number',
  'txt_address': 'Address',
  'txt_payment_info': 'Payment Info',
  'txt_subtotal': 'Subtotal',
  'txt_shipping_fee': 'Shipping Fee',
  'txt_shipping_id': 'Shipping ID',
  'txt_province': 'Province',
  'txt_subdistrict': 'Sub - District',
  'txt_fee': 'Fee (/Kg)',
  'txt_fee_rp': 'Fee (Rp) /Kg',
  'txt_total_incl': 'Total (Incl. Shipping)',
  'txt_vendor_voucher': 'Vendor Voucher',
  'txt_payment_method': 'Payment Method',
  'txt_payment_at': 'Payment At',
  'txt_total_of_payment': 'Total of Payment',
  'txt_redelivery': 'Redelivery',
  'txt_invoice': 'Invoice',
  'txt_label': 'Label',
  'txt_logs': 'Logs',
  'txt_order_delivered': 'Order Delivered',
  'txt_log_order': 'Log Order',
  'txt_detail_order': 'Detail Order',
  'txt_complained_at': 'Complained At',
  'txt_reason': 'Reason',
  'txt_solution_expectation': 'Solution Expectation',
  'txt_photo': 'Photo',
  'txt_solution': 'Solution',
  'txt_cost': 'Cost',
  'txt_cost_of_return': "Cost of Return",
  'txt_cost_of_refund': "Cost of Refund",
  'txt_cost_of_replacement': "Cost of Replacement",
  'txt_cost_of_redelivery': "Cost of Redelivery",
  'txt_complete_complain': 'Complete Complain',
  'txt_continue_to_refund': 'Continue to Refund',
  'txt_input_cost': 'Input Cost',
  'txt_store_info': 'Store Info',
  'txt_increase_sales': 'Increase Sales',
  'txt_promotion': 'Promotion',
  'txt_advertisement': 'Advertisement',
  'txt_account': 'Account',
  'txt_balance': 'Balance',
  'txt_review': 'Review',
  'txt_setting': 'Setting',
  'txt_store_banner': 'Store Banner',
  'txt_detail_banner': 'Detail Banner',
  'txt_edit_banner': 'Edit Banner',
  'txt_add_banner': 'Add Banner',
  'txt_image': 'Image',
  'txt_banner': 'Banner',
  'txt_title': 'Title',
  'txt_url': 'URL',
  'txt_your_store': 'Your Store',
  'txt_store_status': 'Store Status',
  'txt_social_media': 'Social Media',
  'txt_store_name': 'Store Name',
  'txt_store_description': 'Store Description',
  'txt_city': 'City',
  'txt_zip_code': 'Zip Code',
  'txt_instagram': 'Instagram',
  'txt_twitter': 'Twitter',
  'txt_facebook': 'Facebook',
  'txt_youtube': 'YouTube',
  'txt_tiktok': 'TikTok',
  'txt_edit_store_info': 'Edit Store Info',
  'txt_edit_social_media': 'Edit Social Media',
  'txt_disctrict': 'District',
  'txt_upload': 'Upload',
  'txt_upload_photo': 'Upload Photo',
  'txt_take_a_picture': 'Take a Picture',
  'txt_gallery': 'Gallery',
  'txt_owner_profile': 'Owner Profile',
  'txt_owner_name': 'Owner Name',
  'txt_owner_email': 'Owner Email Address',
  'txt_owner_phone_number': 'Phone Number',
  'txt_change_password': 'Change Password',
  'txt_edit_account': 'Edit Account',
  'txt_full_name': 'Full Name',
  'txt_current_password': 'Current Password',
  'txt_new_password': 'New Password',
  'txt_confirm_password': 'Confirm Password',
  'txt_must_be_long': 'Must be 6-20 character long',
  'txt_atleast_alphabet': 'Contain atleast 1 alphabet and 1 number',
  'txt_atleast_capital': 'Contain atleast 1 capital letter',
  'txt_retype_same_password': 'Retype Same Password',
  'txt_language': 'Language',
  'txt_push_notification': 'Push Notification',
  'txt_logout': 'Logout',
  'txt_bahasa': 'Indonesia',
  'txt_english': 'English',
  'txt_account_balance': 'Account Balance',
  'txt_pending_balance': 'Pending Balance',
  'txt_bank_account': 'Bank Account',
  'txt_withdraw': 'Withdraw',
  'txt_transaction_history': 'Transaction History',
  'txt_withdrawal_amount': 'Withdrawal Amount',
  'txt_bank_name': 'Bank Name',
  'txt_account_number': 'Account Number',
  'txt_account_holder_name': 'Account Holder Name',
  'txt_choose_bank': 'Choose Bank',
  'txt_detail_review': 'Detail Review',
  'txt_review_detail': 'Review Detail',
  'txt_created_at': 'Created At',
  'txt_rating': 'Rating',
  'txt_pictures': 'Pictures',
  'txt_offers': 'Offers',
  'txt_requests': 'Requests',
  'txt_success': 'Success',
  'txt_advertisement_type_name': 'Advertisement Type Name',
  'txt_request_detail': 'Request Detail',
  'txt_requested_by': 'Requested By',
  'txt_advertisement_type': 'Advertisement Type',
  'txt_requested_ad_date': 'Requested Ad Date',
  'txt_requested_at': 'Requested At',
  'txt_update_at': 'Update At',
  'txt_request_advertisement': 'Request Advertisement',
  'txt_time': 'Time',
  'txt_select_date': 'Select Date',
  'txt_ad_type': 'Ad Type',
  'txt_select': 'Select',
  'txt_min_transaction': 'Min Transaction',
  'txt_voucher_detail': 'Voucher Detail',
  'txt_voucher_info': 'Voucher Info',
  'txt_voucher_name': 'Voucher Name',
  'txt_voucher_code': 'Voucher Code',
  'txt_voucher_status': 'Voucher Status',
  'txt_voucher_description': 'Voucher Description',
  'txt_voucher_profit': 'Voucher Profit',
  'txt_voucher_type': 'Voucher Type',
  'txt_quota': 'Quota',
  'txt_min_purchase_amount': 'Min Purchase Amount',
  'txt_percentage_discount': 'Percentage Discount',
  'txt_max_discount': 'Max Discount',
  'txt_start_date': 'Start Date',
  'txt_end_date': 'End Date',
  'txt_voucher_period': 'Voucher Period',
  'txt_add_voucher_info': 'Add Voucher Info',
  'txt_add_voucher_profit': 'Add Voucher Profit',
  'txt_add_voucher_period': 'Add Voucher Period',
  'txt_edit_voucher_info': 'Edit Voucher Info',
  'txt_edit_voucher_profit': 'Edit Voucher Profit',
  'txt_edit_voucher_period': 'Edit Voucher Period',
  'txt_fixed_amount': 'Fixed Amount',
  'txt_percentage': 'Percentage',
  'txt_fixed_amount_discount': 'Fixed Amount Discount',
  'txt_time_start': 'Time Start',
  'txt_time_end': 'Time End',
  'txt_sales': 'Sales',
  'txt_commision_ammount': 'Commision Ammount',
  'txt_loss': 'Loss',
  'txt_profile_picture': 'Profile Picture',
  'txt_profile_picture_description':
      'Max. file size is 10 MB with .JPG, JPEG, or PNG format.',
  'txt_change_picture': 'Change Picture',

  // Product Empty State
  'txt_store_empty_title': 'Your store is empty',
  'txt_store_empty_description':
      'Request to upload your product now by tapping the button in the right bottom corner (+)',

  // Chat Empty State
  'txt_chat_empty_title': 'There is no chat from customer',
  'txt_chat_empty_subtitle': 'Stay tuned for chats from customers',

  // Product Review Empty State
  'txt_product_review_empty_title': 'Oops! No review found',
  'txt_product_review_empty_subtitle':
      'It seems no review has been added yet. We\'ll notify you when something new arrives!',

  // Notification
  'txt_notification': 'Notification',
  'txt_mark_as_read': 'Mark all as read',

  // Minimum length
  'txt_minimum_length': 'Minimum 2 character or more',

  'txt_updated_data': 'Data is Successfully Updated',
  'txt_deleted_data': 'Data is Successfully Deleted',

  //BUTTON
  'txt_button_retry': 'Retry',
  'txt_button_change_locale': 'Change Language',
  'txt_button_login': 'Login',
  'txt_button_logout': 'Log out',
  'txt_button_camera': 'Camera',
  'txt_button_gallery': 'Gallery',
  'txt_button_confirm': 'Confirm',
  'txt_forgot_password': 'Forgot Password',
  'txt_edit': 'Edit',
  'txt_next': 'Next',
  'txt_save': 'Save',
  'txt_cancel': 'Cancel',
  'txt_submit': 'Submit',
  'txt_apply': 'Apply',
  'txt_delete': 'Delete',
  'txt_edit_status': 'Edit Status',
  'txt_product_selected': 'Product Selected',
  'txt_financial': 'Financial',
  'txt_close': 'Close',

  // Advertisement empty state
  'txt_offers_empty_title': 'No offers right now',
  'txt_offers_empty_description':
      'Stay tuned! Notifications about advertisement offers will show up here.',
  'txt_request_empty_title': 'No request yet',
  'txt_request_empty_description':
      'It seems you have not requested an advertisement yet',
  // Notification empty state
  'txt_notification_empty_title': 'No offers right now',
  'txt_notification_empty_description':
      'Stay tuned! Notifications about advertisement offers will show up here.',

  // location
  'txt_select_province_first': 'Province is required',
  'txt_select_city_first': 'City is required',

  //Validation
  'txt_valid_email': 'Please enter a valid email address.',
  'txt_valid_password': 'Password must be at least 6 characters.',
  'txt_valid_name': 'Please enter a name.',
  'txt_valid_number': 'Please enter a number.',
  'txt_valid_notEmpty': 'This is a required field.',
  'txt_valid_phone': 'Please enter a valid phone number',
  'txt_valid_keyword': 'The search keyword must be at least 3 characters',
  'txt_phone_must_be_log': 'Must be 9-20 character long',
  'txt_phone_must_be_format': 'Must be started with 085.. etc',

  //Forgot Password
  'txt_email_sended': "Email Sended",
  'txt_email_fail': "Cannot Send Email",

  // request catalog detail status desc
  'txt_request_catalog_detail_description':
      'If product requested has been accepted, it will move to \'Catalog\' tab, and if rejected it will shown by status below.',
};
