const Map<String, String> id = {
  // General Pop Up
  // Delete
  'txt_confirmation_dialog_title': 'Apakah Anda yakin',
  'txt_confirmation_dialog_description':
      'Anda tidak dapat mengembalikan tindakan ini',

  'txt_name': 'name',
  'txt_email': 'Email',
  'txt_password': 'Password',
  'txt_password_confirmation': 'Konfirmasi Password',
  'txt_menu_home': 'Beranda',
  'txt_menu_dialog': 'Dialog',
  'txt_menu_maps': 'Peta',
  'txt_menu_other': 'Lainnya',
  'txt_menu_login': 'Masuk',
  'txt_menu_detail': 'Detil',
  'txt_empty_user': 'Tidak ada data user',
  'txt_error_title': 'Terjadi kesalahan',
  'txt_error_general': 'Oops terjadi kesalahan server...',
  'txt_used': 'Terpakai',

  // Bottom Navigation
  'txt_home': 'Dashboard',
  'txt_order': 'Order',
  'txt_product': 'Produk',
  'txt_message': 'Pesan',
  'txt_store': 'Toko Saya',

  // Onboarding
  'onboard_first': 'Analisis toko Anda dengan dasbor yang sederhana dan mudah',
  'onboard_second': 'Lebih dekat dengan pelanggan melalui obrolan',
  'onboard_third': 'Kelola pesanan Anda dengan fitur yang lebih mudah',
  'skip': 'Lewati',
  'login': 'Masuk',

  // Product
  'txt_catalog': 'Katalog',
  'txt_catalog_active': 'Aktif Katalog',
  'txt_bulk_update': 'Bulk Update',
  'txt_edit_all': 'Ubah Semua',
  'txt_variant': 'Varian',
  'txt_price': 'Harga',
  'txt_discount': 'Diskon',
  'txt_request': 'Rekues',
  'txt_requested': 'Direkues',
  'txt_rejected': 'Ditolak',

  'txt_catalog_detail': 'Detail Katalog',
  'txt_product_detail': 'Detail Produk',
  'txt_product_detail_description': 'Masukkan deskripsi produk',
  'txt_product_image': 'Gambar Produk',
  'txt_product_rating': 'Penilaian Produk',
  'txt_catalog_edit': 'Ubah Katalog',
  'txt_catalog_add': 'Tambah Katalog',

  // Catalog Detail
  'txt_brand': 'Merk',
  'txt_category': 'Kategori',
  'txt_description': 'Deskripsi',
  'txt_variants': 'Varian',
  'txt_variants_description': 'Masukkan deskripsi produk varian tunggal',
  'txt_multi_variants_description': 'Masukkan deskripsi produk multi varian',
  'txt_dimension': 'Dimensi',
  'txt_dimension_description': 'Masukkan Dimensi Produk',

  // Variant
  'txt_single_variant_sku': 'Varian SKU Stauan (Stock Keeping Unit)',
  'txt_multi_variant_sku': 'Varian SKU (Stock Keeping Unit)',
  'txt_normal_price': 'Harga Normal',
  'txt_cost_price': 'Harga Pembelian',
  'txt_cost_price_initial': 'Harga Pembelian (Initial Capital)',
  'txt_discount_price': 'Harga Diskon',
  'txt_weight': 'Berat',
  'txt_color_size': 'Warna / Ukuran',
  'txt_sku': 'SKU',
  'txt_set_multiple_at_once': 'Pilih Semua',
  'txt_set_multiple_at_once_description':
      'Tetapkan SKU, harga, stok, dan lainnya sekaligus',

  // Dimension
  'txt_width': 'Lebar',
  'txt_height': 'Tinggi',
  'txt_depth': 'Dalam',
  // Status
  'txt_status': 'Status',
  'txt_active': 'Aktif',
  'txt_inactive': 'Tidak Aktif',
  // See All
  'txt_see_all': 'Lihat Semua',
  'txt_see_less': 'Lihat Lebih Sedikit',

  'txt_add_up_to': 'Dapat menambahkan hingga 3 gambar',
  'txt_single_variant_title': 'Varian Satuan',
  'txt_multi_variant': 'Multi Varian',
  'txt_add_variations': 'Tambah Variasi',
  'txt_variations': 'Variasi',
  'txt_variation_name': 'Nama Variasi',
  'txt_option_name': 'Nama Opsi',

  'txt_total_of_order': 'Total Pesanan',
  'txt_day': 'Hari',
  'txt_month': 'Bulan',
  'txt_year': 'Tahun',
  'txt_all_period': 'Semua Periode',
  'txt_sold': 'Terjual',
  'txt_chat': 'Obrolan',
  'txt_type_message_here': 'Ketik pesan disini',
  'txt_select_variant': 'Pilih Varian',
  'txt_select_all': 'Pilih Semua',
  'txt_set': 'Set',
  'txt_remove_variation': 'Hapus Variasi',
  'txt_choose_date': 'Pilih Tanggal',

  'txt_filter': 'Filter',
  'txt_reset': 'Reset',
  'txt_all': 'Semua',
  'txt_unread': 'Belum Dibaca',
  'txt_read': 'Sudah Dibaca',
  'txt_date': 'Tanggal',

  // Variant Detail
  'txt_variant_detail': 'Detail Varian',

  // Variant Edit
  'txt_variant_edit': 'Ubah Varian & Inventori',
  'txt_variant_edit_single_sku': 'SKU Varian Satuan (Stock Keeping Unit)',
  'txt_variant_edit_sku': 'Varian SKU (Stock Keeping Unit)',
  'txt_variant_edit_normal_price': 'Harga Normal (Rp)',
  'txt_variant_edit_cost_price': 'Harga Pembelian (Initial Capital) (Rp)',
  'txt_variant_edit_discount_price': 'Harga Diskon (Rp)',
  'txt_variant_edit_weight': 'Berat (Kg)',

  // Brand Detail
  'txt_brand_detail': 'Detail Merk',
  'txt_brand_name': 'Nama Merk',
  'txt_brand_description': 'Deskripsi Merk',
  // Brand Add
  'txt_brand_add': 'Tambah Merk',
  'txt_brand_add_name': 'Nama Merk',
  'txt_brand_add_description': 'Deskripsi',
  'txt_input_brand_name': 'Masukkan Nama Merk',
  'txt_input_brand_description': 'Masukkan Deskripsi',

  // Dashboard
  'txt_store_analysis': 'Analisis Toko',
  'txt_product_sold': 'Produk Terjual',
  'txt_store_visit': 'Kunjungi Toko',
  'txt_last_day': 'vs Hari Terakhir',
  'txt_profit': 'Keuntungan',
  'txt_sales_revenue': 'Pendapatan Penjualan',
  'txt_cost_of_product': 'Biaya Produk',
  'txt_cost_of_voucher_discount': 'Biaya Diskon Voucher',
  'txt_cost_of_commision': 'Biaya Komisi',
  'txt_cost_of_complained_order': 'Biaya Pesanan yang Dikomplain',

  'txt_stock_reminder': 'Pengingat Stok',
  'txt_product_name': 'Nama Produk',
  'txt_out_of_stock': 'Habis',
  'txt_show_more': 'Tampilkan Lebih Banyak',
  'txt_show_less': 'Tampilkan Lebih Sedikit',

  'txt_color': 'Warna',
  'txt_add_option': 'Tambah Opsi',
  'txt_size': 'Ukuran',
  'txt_order_detail': 'Detail Pesanan',

  'txt_most_sold_product': 'Produk Terlaris',
  'txt_top_product': 'Produk Unggulan',
  'txt_stock': 'Stok',

  // Order
  'txt_search_voucher': 'Cari Voucher',
  'txt_search': 'Cari',
  'txt_paid': 'Dibayar',
  'txt_on_process': 'Diproses',
  'txt_on_delivery': 'Diantar',
  'txt_delivered': 'Diterima',
  'txt_process': 'Proses',
  'txt_waiting_for_payment': 'Menunggu Pembayaran',
  'txt_on_processed': 'Sedang Diproses',
  'txt_completed': 'Diselesaikan',
  'txt_canceled': 'Dibatalkan',
  'txt_complained': 'Dikomplain',
  'txt_waiting_for_refund': 'Menunggu Pengembalian Dana',
  'txt_waiting_for_return_and_refund': 'Menunggu Pengembalian Barang dan Dana',
  'txt_sort': 'Urutkan',
  'txt_shipment_method': 'Metode Pengiriman',
  'txt_deliver_order': 'Kirim Pesanan',
  'txt_delivery_receipt': 'Delivery Receipt',
  'txt_waiting_for_replacement': 'Menuggu Penukaran Barang',
  'txt_waiting_for_redelivery': 'Menunggu Pengiriman Ulang',
  'txt_waiting_for_return': 'Menunggu Pengembalian Barang',
  'txt_waiting_payment': 'Menunggu Pembayaran',
  'txt_cancelled': 'Dibatalkan',
  'txt_input_receipt': 'Masukkan Tanda Terima',
  'txt_order_status': 'Status Pesanan',
  'txt_order_id': 'ID Pesanan',
  'txt_invoice_id': 'ID Invoice',
  'txt_ordered_at': 'Dipesan Pada',
  'txt_customer': 'Kustomer',
  'txt_phone': 'Telepon',
  'txt_notes': 'Catatan',
  'txt_product_list': 'List Produk',
  'txt_shipping': 'Pengiriman',
  'txt_courier': 'Kurir',
  'txt_self_delivery': 'Pengiriman Mandiri',
  'txt_jnt': 'JNT',
  'txt_sicepat': 'SiCepat',
  'txt_pos': 'Pos Indonesia',
  'txt_tracking_number': 'No. Resi',
  'txt_address': 'Alamat',
  'txt_payment_info': 'Info Pembayaran',
  'txt_subtotal': 'Subtotal',
  'txt_shipping_fee': 'Biaya Pengiriman',
  'txt_shipping_id': 'ID Pengiriman',
  'txt_province': 'Provinsi',
  'txt_subdistrict': 'Kecamatan',
  'txt_fee': 'Biaya (/Kg)',
  'txt_fee_rp': 'Biaya (Rp) /Kg',
  'txt_total_incl': 'Total (Termasuk. Pengiriman)',
  'txt_vendor_voucher': 'Voucher Vendor',
  'txt_payment_method': 'Metode Pembayaran',
  'txt_payment_at': 'Dibayarkan Pada',
  'txt_total_of_payment': 'Total Pembayaran',
  'txt_redelivery': 'Pengiriman Ulang',
  'txt_invoice': 'Invoice',
  'txt_label': 'Label',
  'txt_logs': 'Logs',
  'txt_order_delivered': 'Pesanan Terkirim',
  'txt_log_order': 'Log Pesanan',
  'txt_detail_order': 'Detail Pesanan',
  'txt_complained_at': 'Dikomplain Pada',
  'txt_reason': 'Alasan',
  'txt_solution_expectation': 'Ekspektasi Solusi',
  'txt_photo': 'Foto',
  'txt_solution': 'Solusi',
  'txt_cost': 'Biaya',
  'txt_completed_complained': 'Komplain Diselesaikan',
  'txt_rejected_complained': 'Komplain Ditolak',
  'txt_owner_profile': 'Profil Pemilik',
  'txt_owner_name': 'Nama Pemilik',
  'txt_owner_email': 'Alamat Email Pemilik',
  'txt_owner_phone_number': 'Nomor Telepon',
  'txt_cost_complain': "Biaya",
  'txt_cost_of_return': "Biaya Pengembalian Barang",
  'txt_cost_of_refund': "Biaya Pengembalian Dana",
  'txt_cost_of_replacement': "Biaya Penggantian Barang",
  'txt_cost_of_redelivery': "Biaya Pengiriman Ulang",
  'txt_complete_complain': 'Lengkapi Komplain',
  'txt_continue_to_refund': 'Lanjutkan Pengembalian Dana',
  'txt_input_cost': 'Masukkan Biaya',
  'txt_store_info': 'Info Toko',
  'txt_increase_sales': 'Menaikkan Penjualan',
  'txt_promotion': 'Promosi',
  'txt_advertisement': 'Iklan',
  'txt_account': 'Akun',
  'txt_balance': 'Saldo',
  'txt_review': 'Review',
  'txt_setting': 'Pengaturan',
  'txt_store_banner': 'Banner Toko',
  'txt_detail_banner': 'Detail Banner',
  'txt_edit_banner': 'Ubah Banner',
  'txt_add_banner': 'Tambah Banner',
  'txt_image': 'Gambar',
  'txt_banner': 'Banner',
  'txt_title': 'Judul',
  'txt_url': 'URL',
  'txt_city': 'Kota',
  'txt_zip_code': 'Kode Pos',
  'txt_instagram': 'Instagram',
  'txt_twitter': 'Twitter',
  'txt_facebook': 'Facebook',
  'txt_youtube': 'YouTube',
  'txt_tiktok': 'TikTok',
  'txt_edit_store_info': 'Ubah Info Toko',
  'txt_edit_social_media': 'Ubah Media Sosial',
  'txt_disctrict': 'District',
  'txt_upload': 'Unggah',
  'txt_upload_photo': 'Unggah Gambar',
  'txt_take_a_picture': 'Ambil Gambar',
  'txt_gallery': 'Galeri',
  'txt_vendor_notes': "Catatan Vendor",

  'txt_change_password': 'Ganti Kata Sandi',
  'txt_edit_account': 'Ubah Akun',
  'txt_full_name': 'Nama Lengkap',
  'txt_current_password': 'Kata Sandi Saat Ini',
  'txt_new_password': 'Kata Sandi Baru',
  'txt_confirm_password': 'Konfirmasi Kata Sandi',
  'txt_must_be_long': 'Memiliki 6-20 jumlah karakter',
  'txt_atleast_alphabet': 'Mengandung setidaknya 1 huruf dan 1 angka',
  'txt_atleast_capital': 'Mengandung setidaknya 1 huruf kapital',
  'txt_retype_same_password': 'Tuliskan Kata Sandi Yang Sama',
  'txt_language': 'Bahasa',
  'txt_push_notification': 'Push Notification',
  'txt_logout': 'Keluar',
  'txt_bahasa': 'Indonesia',
  'txt_english': 'English',
  'txt_account_balance': 'Saldo Akun',
  'txt_pending_balance': 'Saldo Tertunda',
  'txt_bank_account': 'Akun Bank',
  'txt_withdraw': 'Tarik Saldo',
  'txt_transaction_history': 'Riwayat Transaksi',
  'txt_withdrawal_amount': 'Withdrawal Amount',
  'txt_bank_name': 'Nama Bank',
  'txt_account_number': 'Nomor Rekening',
  'txt_account_holder_name': 'Nama Pemilik Rekening',
  'txt_choose_bank': 'Pilih Bank',
  'txt_detail_review': 'Detail Review',
  'txt_review_detail': 'Review Detail',
  'txt_created_at': 'Dibuat Pada',
  'txt_rating': 'Rating',
  'txt_pictures': 'Foto',
  'txt_offers': 'Penawaran',
  'txt_requests': 'Requests',
  'txt_success': 'Sukses',
  'txt_advertisement_type_name': 'Nama Tipe Iklan',
  'txt_request_detail': 'Detail Request Request',
  'txt_requested_by': 'Requested By',
  'txt_advertisement_type': 'Tipe Iklan',
  'txt_requested_ad_date': 'Tanggal Request Iklan',
  'txt_requested_at': 'Requested At',
  'txt_update_at': 'Diubah Pada',
  'txt_request_advertisement': 'Request Iklan',
  'txt_time': 'Waktu',
  'txt_select_date': 'Pilih Tanggal',
  'txt_ad_type': 'Tipe Iklan',
  'txt_select': 'Pilih',
  'txt_min_transaction': 'Min. Transaksi',
  'txt_voucher_detail': 'Detail Voucher',
  'txt_voucher_info': 'Info Voucher',
  'txt_voucher_name': 'Nama Voucher',
  'txt_voucher_code': 'Kode Voucher',
  'txt_voucher_status': 'Status Voucher',
  'txt_voucher_description': 'Deskripsi Voucher',
  'txt_voucher_profit': 'Keuntungan Voucher',
  'txt_voucher_type': 'Tipe Voucher',
  'txt_quota': 'Kuota',
  'txt_min_purchase_amount': 'Jumlah Minimal Pembelian',
  'txt_percentage_discount': 'Persentase Diskon',
  'txt_max_discount': 'Maksimum Diskon',
  'txt_start_date': 'Tanggal Mulai',
  'txt_end_date': 'Tanggal Berakhir',
  'txt_voucher_period': 'Periode Voucher',
  'txt_add_voucher_info': 'Tambah Info Voucher',
  'txt_add_voucher_profit': 'Tambah Profit Voucher',
  'txt_add_voucher_period': 'Tambah Periode Voucher',
  'txt_edit_voucher_info': 'Ubah Info Voucher',
  'txt_edit_voucher_profit': 'Ubah Profit Voucher',
  'txt_edit_voucher_period': 'Ubah Periode Voucher',
  'txt_fixed_amount': 'Jumlah Tetap',
  'txt_percentage': 'Persentase',
  'txt_fixed_amount_discount': 'Diskon Jumlah Tetap',
  'txt_time_start': 'Waktu Mulai',
  'txt_time_end': 'Waktu Berakhir',
  'txt_sales': 'Penjualan',
  'txt_commision_ammount': 'Jumlah Komisi',
  'txt_loss': 'Kerugian',
  'txt_profile_picture': 'Foto Profil',
  'txt_profile_picture_description':
      'Ukuran Maksimum file adalah 10MB dengan format JPG, JPEG, atau PNG.',
  'txt_change_picture': 'Ganti Foto',

  // Notification
  'txt_notification': 'Notifikasi',
  'txt_mark_as_read': 'Tandai Semua telah dibaca',

  'txt_updated_data': 'Data Berhasil Diubah',
  'txt_deleted_data': 'Data Berhasil Dihapus',

  // store
  'txt_your_store': 'Toko Anda',
  'txt_store_status': 'Status Toko',
  'txt_social_media': 'Media Sosial',
  'txt_store_name': 'Nama Toko',
  'txt_store_description': 'Deskripsi Toko',

  //BUTTON
  'txt_button_retry': 'Coba Lagi',
  'txt_button_change_locale': 'Ganti Bahasa',
  'txt_button_login': 'Masuk',
  'txt_button_register': 'Daftar',
  'txt_button_logout': 'Keluar',
  'txt_button_camera': 'Kamera',
  'txt_button_gallery': 'Album',
  'txt_button_confirm': 'Konfirmasi',
  'txt_forgot_password': 'Lupa Sandi',
  'txt_edit': 'Ubah',
  'txt_next': 'Selanjutnya',
  'txt_save': 'Simpan',
  'txt_cancel': 'Batal',
  'txt_submit': 'Simpan',
  'txt_apply': 'Terapkan',
  'txt_delete': 'Hapus',
  'txt_edit_status': 'Ubah Status',
  'txt_product_selected': 'Produk Terpilih',
  'txt_financial': 'Keuangan',
  'txt_close': 'Tutup',

  //Validation
  'txt_valid_email': 'Format email masih salah',
  'txt_valid_password': 'Minimal password adalah 6 karakter',
  'txt_valid_name': 'Silahkan masukkan Nama anda',
  'txt_valid_number': 'Silahkan masukkan nomer yang benar',
  'txt_valid_notEmpty': 'Kolom tidak boleh kosong',
  'txt_valid_phone': 'Masukkan nomor telepon yang valid',
  'txt_valid_keyword': 'Minimal kata kunci adalah 3 karakter',
  'txt_phone_must_be_log': 'Nomor telepon harus memiliki 9-20 karakter',
  'txt_phone_must_be_format': 'Harus diawali dengan 085... dst',

  // Product Empty State
  'txt_store_empty_title': 'Toko Anda Kosong',
  'txt_store_empty_description':
      'Unggah produk sekarang dengan menekan tombol (+) di pojok kanan bawah',

  // Chat Empty State
  'txt_chat_empty_title': 'Tidak ada pesan dari pelanggan',
  'txt_chat_empty_subtitle': 'Tetap nantikan pesan dari pelanggan',

  // Product Review Empty State
  'txt_product_review_empty_title': 'Tidak ada review',
  'txt_product_review_empty_subtitle':
      'Belum ada ulasan yang ditambahkan. Kami akan memberi tahu anda saat sesuatu yang baru datang!',

  // Advertisement empty state
  'txt_offers_empty_title': 'Tidak ada penawaran saat ini',
  'txt_offers_empty_description':
      'Pantau terus! Pemberitahuan tentang tawaran iklan akan muncul di sini.',
  'txt_request_empty_title': 'Tidak ada request',
  'txt_request_empty_description': 'Tidak ada permintaan',
  // Notification empty state
  'txt_notification_empty_title': 'Tidak ada notifikasi',
  'txt_notification_empty_description':
      'Pantau terus! Pemberitahuan tentang tawaran iklan akan muncul di sini.',

  // location
  'txt_select_province_first': 'Nama provinsi tidak boleh kosong',
  'txt_select_city_first': 'Nama kota tidak boleh kosong',

  // Minimum length
  'txt_minimum_length': 'Minimal 2 karakter atau lebih',

  //Forgot Password
  'txt_email_sended': "Email Terkirim",
  'txt_email_fail': "Tidak Dapat Mengirim Email",

  // request catalog detail status desc
  'txt_request_catalog_detail_description':
      'Jika produk yang diminta telah diterima, maka akan pindah ke tab \'Katalog\', dan jika ditolak akan ditampilkan dengan status di bawah ini.',
};
